const testDataUser = [
    {
        id: 1,
        name: 'Bohdan',
        surname: 'Borysenko',
        patronymic: 'Serhiyovych',
        classID: 2,
        email: 'email@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 4,
        name: 'Artem',
        surname: 'Mykytenko',
        patronymic: 'Anatoliyovych',
        classID: 2,
        email: 'email2@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 5,
        name: 'Ivan',
        surname: 'Mishchanyn',
        patronymic: 'Ivanovych',
        classID: 1,
        email: 'email3@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 6,
        name: 'Petro',
        surname: 'Kucenko',
        patronymic: 'Petrovych',
        classID: 2,
        email: 'email4@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 7,
        name: 'Andriy',
        surname: 'Melnyk',
        patronymic: 'Andriyovych',
        classID: 2,
        email: 'email5@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 8,
        name: 'Stepan',
        surname: 'Stecenko',
        patronymic: 'Stepanovych',
        classID: 1,
        email: 'email6@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 9,
        name: 'Olexandr',
        surname: 'Chumack',
        patronymic: 'Olexandrovych',
        classID: 2,
        email: 'email7@gmail.com',
        password: 'password',
        role: 1
    },
    {
        id: 10,
        name: 'Teacher',
        surname: 'Teacherenko',
        patronymic: 'Teacherovych',
        classID: 5,
        email: 'email7@gmail.com',
        password: 'password',
        role: 2
    },
    {
        id: 11,
        name: 'Andriy',
        surname: 'Andrienko',
        patronymic: 'Andriyovych',
        classID: 6,
        email: 'email7@gmail.com',
        password: 'password',
        role: 2
    },
    {
        id: 12,
        name: 'Stepan',
        surname: 'Stepanenko',
        patronymic: 'Stepanovych',
        classID: 3,
        email: 'email7@gmail.com',
        password: 'password',
        role: 2
    },
    {
        id: 13,
        name: 'Ivan',
        surname: 'Ivanenko',
        patronymic: 'Ivanovych',
        classID: 4,
        email: 'email7@gmail.com',
        password: 'password',
        role: 2
    }
]
let testClass = [
    {id: 1, name: '10-Б', teacherId: 2},
    {id: 2, name: '10-А', teacherId: 1},
]
// const testDataTeachers = [
//     {id: 1, name: 'Teacher', surname: 'Teacherenko', patronymic: 'Teacherovych', classID: 2, email: 'email7@gmail.com', password: 'password', role: 2},
//     {id: 2, name: 'Andriy', surname: 'Andrienko', patronymic: 'Andriyovych', classID: 6, email: 'email7@gmail.com', password: 'password', role: 2},
//     {id: 3, name: 'Stepan', surname: 'Stepanenko', patronymic: 'Stepanovych', classID: 3, email: 'email7@gmail.com', password: 'password', role: 2},
//     {id: 4, name: 'Ivan', surname: 'Ivanenko', patronymic: 'Ivanovych', classID: 4, email: 'email7@gmail.com', password: 'password', role: 2}
// ]
const testDataSubjects = [
    {id: 1, name: 'Математика', teacherId: 2, classId: 2, studyPlan: 1, other: '', link: 'https://us04web.zoom.us/j/9937940977?pwd=Y1praFZJdkhXQTliemFBZkZVZmxUUT09#success'},
    {id: 2, name: 'Алгебра', teacherId: 2, classId: 1, studyPlan: 2, other: '', link: ''},
    {id: 3, name: 'Геометрія', teacherId: 2, classId: 2, studyPlan: 1, other: '', link: ''},
    {id: 4, name: 'Фізика', teacherId: 2, classId: 2, studyPlan: 1, other: '', link: ''},

];
const testDataStudyPlans = [
    {id: 1, name: 'Основний', teacherId: 2, classNumber: 10},
    {id: 2, name: 'Основний2', teacherId: 2, classNumber: 10},
]

// Таблиця Багато до багатьох для зв'язку навчальних планів та подій
const testDataPlansEvents = [
    {planId: 1, eventId: 1},
    {planId: 1, eventId: 2},
    {planId: 1, eventId: 3},
    {planId: 1, eventId: 4},
    {planId: 1, eventId: 5},
    {planId: 1, eventId: 6},
    {planId: 2, eventId: 5},
]
const testDataStudyEvents = [
    {id: 1, name: 'Додавання дробів', shortName: 'КР1', typeId: 1},
    {id: 2, name: 'Інтеграли', shortName: 'КР2', typeId: 1},
    {id: 3, name: 'Похідні', shortName: 'КР3', typeId: 1},
    {id: 4, name: 'Границі функцій', shortName: 'СР1', typeId: 2},
    {id: 5, name: 'Інтеграли 2-го порядку', shortName: 'КР4', typeId: 1},
    {id: 6, name: 'Первісна функції', shortName: 'СР2', typeId: 2}
]
const testTypesEvents = [
    {id: 1, type: 'Контрольна робота'},
    {id: 2, type: 'Самостійна робота'},
    {id: 3, type: 'Семестрова робота'},
    {id: 4, type: 'Диктант'},
]
// const testDataMarks = [
//     {id: 1, subjectId: 1, studentId: 20, mark: 8, eventId: 1}
// ]
const globalMarksArray = {
    '10-A Алгебра': [
        {
            key: '0',
            name: 'Тестовий учень',
            id: 1,
            'Тема 1': 12,
            'Тема 2': 10,
            'Самостійна 1': 8,
            'Тема 4': '',
            'Тема 5': '',
            'Тема 6': 7,
            'Самостійна 2': '',
            'Тема 7': 10,
            'Тема 8': 12,
            'Контрольна 1': 6,
            'Тема 9': '',
            'Тема 10': 10,
            'Самостійна 3': 10,
            'Тема 11': 8,
            'Тема 12': 10,
            'Тема 13': 12,
            'Самостійна 4': '',
            'Тема 14': '',
            'Тема 15': '',
            'Контрольна 2': '',
            'Семестрова': '',
        },
        {
            key: '1',
            name: 'Тестовий учень',
            id: 2,
            'Тема 1': 12,
            'Тема 2': 10,
            'Самостійна 1': '',
            'Тема 4': 6,
            'Тема 5': 9,
            'Тема 6': 7,
            'Самостійна 2': 12,
            'Тема 7': '',
            'Тема 8': 12,
            'Контрольна 1': 6,
            'Тема 9': 9,
            'Тема 10': 10,
            'Самостійна 3': '',
            'Тема 11': 8,
            'Тема 12': 10,
            'Тема 13': 12,
            'Самостійна 4': 8,
            'Тема 14': '',
            'Тема 15': '',
            'Контрольна 2': '',
            'Семестрова': '',
        },
        {
            key: '2',
            name: 'Тестовий учень',
            id: 3,
            'Тема 1': 12,
            'Тема 2': 10,
            'Самостійна 1': 8,
            'Тема 4': 12,
            'Тема 5': 10,
            'Тема 6': 7,
            'Самостійна 2': 7,
            'Тема 7': 10,
            'Тема 8': 12,
            'Контрольна 1': 6,
            'Тема 9': 9,
            'Тема 10': 10,
            'Самостійна 3': 10,
            'Тема 11': 8,
            'Тема 12': 10,
            'Тема 13': 12,
            'Самостійна 4': 11,
            'Тема 14': '',
            'Тема 15': '',
            'Контрольна 2': '',
            'Семестрова': '',
        },
        {
            key: '3',
            name: 'Тестовий учень',
            id: 4,
            'Тема 1': 12,
            'Тема 2': 10,
            'Самостійна 1': 8,
            'Тема 4': '',
            'Тема 5': '',
            'Тема 6': 7,
            'Самостійна 2': '',
            'Тема 7': 10,
            'Тема 8': 12,
            'Контрольна 1': 6,
            'Тема 9': '',
            'Тема 10': 10,
            'Самостійна 3': 10,
            'Тема 11': 8,
            'Тема 12': 10,
            'Тема 13': 12,
            'Самостійна 4': '',
            'Тема 14': '',
            'Тема 15': '',
            'Контрольна 2': '',
            'Семестрова': '',
        },
        {
            key: '4',
            name: 'Тестовий учень',
            id: 5,
            'Тема 1': '',
            'Тема 2': 10,
            'Самостійна 1': 8,
            'Тема 4': 7,
            'Тема 5': 9,
            'Тема 6': 7,
            'Самостійна 2': 10,
            'Тема 7': 10,
            'Тема 8': '',
            'Контрольна 1': 9,
            'Тема 9': '',
            'Тема 10': 10,
            'Самостійна 3': 10,
            'Тема 11': 8,
            'Тема 12': 10,
            'Тема 13': 12,
            'Самостійна 4': '',
            'Тема 14': '',
            'Тема 15': '',
            'Контрольна 2': '',
            'Семестрова': '',
        },
    ],
    '11-Б Українська мова': [
        {
            key: '0',
            name: 'Тестовий учень',
            id: 1,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': '',
            'Твір 1': '',
            'Переказ 1': 7,
            'Самостійна 2': '',
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 2,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 2,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 3,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 4,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 5,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 6,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 7,
            'Тема 1': 12,
            'Диктант 1': 10,
            'Самостійна 1': 8,
            'Тема 4': 10,
            'Твір 1': 12,
            'Переказ 1': 7,
            'Самостійна 2': 8,
            'Тема 7': 10,
            'Твір 2': 12,
            'Семестрова': 6,
        },
    ],
    '5-Б Інформатика': [
        {
            key: '0',
            name: 'Тестовий учень',
            id: 1,
            'Практична 1': 12,
            'Практична 2': 10,
            'Практична 3': 8,
            'Практична 4': 10,
            'Практична 5': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 1,
            'Практична 1': 12,
            'Практична 2': 10,
            'Практична 3': 8,
            'Практична 4': 10,
            'Практична 5': 12,
            'Семестрова': 6,
        },
        {
            key: '0',
            name: 'Тестовий учень',
            id: 1,
            'Практична 1': 12,
            'Практична 2': 10,
            'Практична 3': 8,
            'Практична 4': 10,
            'Практична 5': 12,
            'Семестрова': 6,
        },
    ],
}
const globalPupilMarksArray = {
    'Алгебра': {
        'Тема 1': 12,
        'Тема 2': 10,
        'Самостійна 1': 8,
        'Тема 4': '',
        'Тема 5': '',
        'Тема 6': 7,
        'Самостійна 2': '',
        'Тема 7': 10,
        'Тема 8': 12,
        'Контрольна 1': 6,
        'Тема 9': '',
        'Тема 10': 10,
        'Самостійна 3': 10,
        'Тема 11': 8,
        'Тема 12': 10,
        'Тема 13': 12,
        'Самостійна 4': '',
        'Тема 14': '',
        'Тема 15': '',
        'Контрольна 2': '',
        'Семестрова': '',
    },
    'Українська мова': {
        'Тема 1': 12,
        'Диктант 1': 10,
        'Самостійна 1': 8,
        'Тема 4': '',
        'Твір 1': '',
        'Переказ 1': 7,
        'Самостійна 2': '',
        'Тема 7': 10,
        'Твір 2': 12,
        'Семестрова': 6,
    },
    'Інформатика': {
        'Практична 1': 12,
        'Практична 2': 10,
        'Практична 3': 8,
        'Практична 4': 10,
        'Практична 5': 12,
        'Семестрова': 6,
    }
}

exports.users = testDataUser;
exports.subjects = testDataSubjects;
exports.studyPlans = testDataStudyPlans;
exports.studyEvents = testDataStudyEvents;
exports.globalMarks = globalMarksArray;
exports.pupilMarks = globalPupilMarksArray;
//exports.teachers = globalMarksArray;
exports.class = testClass;
exports.plansEvents = testDataPlansEvents;
exports.typesEvents = testTypesEvents;
