export const TeacherActions = {
    SET_MARKS: 'SET_MARKS',
    LOADING: 'LOADING',
    SET_STATUS_MESSAGE: 'SET_STATUS_MESSAGE',
    SET_SUBJECTS: 'SET_SUBJECTS',
    SET_TYPES: 'SET_TYPES',
    SET_PLANS: 'SET_PLANS',
    ADD_NEW_PLAN: 'ADD_NEW_PLAN',
    DELETE_PLAN: 'DELETE_PLAN',
    CHANGE_PLAN: 'CHANGE_PLAN',
    UPDATE_SUBJECT: 'UPDATE_SUBJECT',
    CHANGE_MARKS: 'CHANGE_MARKS',
}

